[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "syapi"
version = "0.1.8"
requires-python = ">=3.11"
description = "library to connect to microservice's ecosystem using API"
dependencies = {file = "requirements.txt"}
