URL_MICROSERVICE_AUTH = 'https://auth.intera.space'
URL_MICROSERVICE_FACI = 'https://solveit.fun'
URL_MICROSERVICE_NOTE = 'https://cachebrain.fun'
URL_MICROSERVICE_PLATFORM = 'https://intera.space'
URL_MICROSERVICE_RESOURCE = 'https://resource.intera.space'
